# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/rlm_lisette_v2.ipynb.

# %% auto #0
__all__ = ['REPL_SYSTEM_PROMPT', 'llm_query', 'run_repl', 'prep_shell', 'rlm', 'tool_mermaid', 'mm', 'print_history',
           'generate_massive_context', 'RLM']

# %% ../nbs/rlm_lisette_v2.ipynb #8410b7af
import os
import json
import random
try:
    from litellm import register_model
except Exception:
    register_model = None  # litellm not available in CI; dependent code should handle this

# %% ../nbs/rlm_lisette_v2.ipynb #2f244ea8
#| eval: false
from lisette import *

# %% ../nbs/rlm_lisette_v2.ipynb #4fcf17c7
try:
    from toolslm.shell import get_shell
except Exception:
    def get_shell():
        raise ModuleNotFoundError("toolslm is required for REPL support. Install toolslm to use this feature.")

# %% ../nbs/rlm_lisette_v2.ipynb #fa40f93f
try:
    import litellm
except Exception:
    class _LiteLLMStub:
        def __getattr__(self, _name):
            raise ModuleNotFoundError(
                "litellm is required for LLM calls. Install litellm to use this feature."
            )
    litellm = _LiteLLMStub()

# %% ../nbs/rlm_lisette_v2.ipynb #1a35f29e
def llm_query(query: str, model="openai/gpt-oss-120b", 
              base_url="https://openrouter.ai/api/v1", 
              api_key=os.getenv("OPENROUTER_API_KEY")):
    msg = mk_msg(query)
    response = litellm.completion(model, [msg], base_url=base_url, api_key=api_key)
    return response.choices[0].message.content


# %% ../nbs/rlm_lisette_v2.ipynb #962ca485
def run_repl(python_code: str, shell=None) -> str:
    "Execute Python code in the REPL environment"
    shell = shell or globals().get("sh")
    if shell is None:
        return "Error: no REPL shell available"
    result = shell.run_cell(python_code)
    if result.error_in_exec or result.error_before_exec:
        return f"Error: {result.error_in_exec or result.error_before_exec}"
    output = result.stdout or ""
    if result.result is not None:
        output += str(result.result)
    return output[:5000]  # truncate long outputs

# %% ../nbs/rlm_lisette_v2.ipynb #6a318f60
def prep_shell(context, model="openai/gpt-oss-20b", base_url="https://openrouter.ai/api/v1", api_key=os.getenv("OPENROUTER_API_KEY")):
    def llm_query(query: str, max_tokens: int = 8096):
        msg = mk_msg(query)
        response = litellm.completion(model, [msg], base_url=base_url, api_key=api_key, max_tokens=max_tokens)
        return response.choices[0].message.content

    sh = get_shell()
    sh.user_ns['context'] = context
    sh.user_ns['llm_query'] = llm_query
    return sh


# %% ../nbs/rlm_lisette_v2.ipynb #56c28380
def rlm(query, context, 
        root_model="openai/gpt-oss-120b",
        sub_model="openai/gpt-oss-20b",
        base_url="https://openrouter.ai/api/v1",
        api_key=os.getenv("OPENROUTER_API_KEY"),
        max_tokens=8096):
    """
    Run a Recursive Language Model query over a context.

    Uses a Python REPL environment where the context is stored as a
    variable, and the root LM can recursively call a sub-LM to
    analyze chunks of that context.

    Parameters
    ----------
    query : str
        The question or instruction to answer using the context.
    context : str
        The context string to make available in the REPL.
    root_model : str, optional
        Model for the outer/root LM that orchestrates the REPL.
    sub_model : str, optional
        Model for recursive sub-LM calls from within the REPL.
    base_url : str, optional
        API base URL for the LLM provider.
    api_key : str, optional
        API key for the LLM provider.
    max_tokens : int, optional
        Maximum output tokens for the root model.

    Returns
    -------
    str
        The root LM's final answer to the query.

    Examples
    -------
    
    """
    register_model({root_model: {"max_output_tokens": max_tokens}})

    def llm_query(q: str):
        msg = mk_msg(q)
        resp = litellm.completion(sub_model, [msg], base_url=base_url, api_key=api_key)
        return resp.choices[0].message.content

    sh = get_shell()
    sh.user_ns['context'] = context
    sh.user_ns['llm_query'] = llm_query

    def run_repl(python_code: str) -> str:
        "Execute Python code in the REPL environment"
        result = sh.run_cell(python_code)
        if result.error_in_exec or result.error_before_exec:
            return f"Error: {result.error_in_exec or result.error_before_exec}"
        output = result.stdout or ""
        if result.result is not None:
            output += str(result.result)
        return output[:5000]

    chat = Chat(
        model=root_model, sp=REPL_SYSTEM_PROMPT, tools=[run_repl],
        api_base=base_url, api_key=api_key
    )
    return chat(query)




# %% ../nbs/rlm_lisette_v2.ipynb #e8bbe39c
REPL_SYSTEM_PROMPT = """You are tasked with answering a query with associated context. You can access, transform, and analyze this context interactively in a REPL environment that can recursively query sub-LLMs, which you are strongly encouraged to use as much as possible. You will be queried iteratively until you provide a final answer.

Your REPL has:
- A `context` variable (string) containing important information about your query
- An `llm_query(query: str)` function that allows you to query an LLM (that can handle around 500K chars) inside your REPL environment.

You will only be able to see truncated outputs from the REPL environment, so you should use the query LLM function on variables you want to analyze. You will find this function especially useful when you have to analyze the semantics of the context. Use these variables as buffers to build up your final answer.

Make sure to explicitly look through the entire context in REPL before answering your query. An example strategy is to first look at the context and figure out a chunking strategy, then break up the context into smart chunks, and query an LLM per chunk with a particular question and save the answers to a buffer, then query an LLM with all the buffers to produce your final answer.

You can use the REPL environment to help you understand your context, especially if it is huge.

Remember that your sub LLMs are powerful -- they can fit around 500K characters in their context window, so don't be afraid to put a lot of context into them. For example, a viable strategy is to feed 10 documents per sub-LLM query. Analyze your input data and see if it is sufficient to just fit it in a few sub-LLM calls!

For example, say we want our recursive model to search for the magic number in the context (assuming the context is a string), and the context is very long, so we want to chunk it:
```python
chunk = context[:10000]
answer = llm_query(f"What is the magic number in the context? Here is the chunk: {{chunk}}")
print(answer)
```

As another example, after analyzing the context and realizing its separated by Markdown headers, we can maintain state through buffers by chunking the context by headers, and iteratively querying an LLM over it:
```python
# After finding out the context is separated by Markdown headers, we can chunk, summarize, and answer
import re
sections = re.split(r'### (.+)', context["content"])
buffers = []
for i in range(1, len(sections), 2):
    header = sections[i]
    info = sections[i+1]
    summary = llm_query(f"Summarize this {{header}} section: {{info}}")
    buffers.append(f"{{header}}: {{summary}}")
final_answer = llm_query(f"Based on these summaries, answer the original query: {{query}}\\n\\nSummaries:\\n" + "\\n".join(buffers))
```

IMPORTANT:
- Always inspect the `context` variable first before answering
- The context can be VERY LONG (millions of tokens). Never print it directly!
- Use Python to explore it safely: check length with len(), peek at slices, search with regex, chunk it
2. A `llm_query` function that allows you to query an LLM (that can handle around 500K chars) inside your REPL environment.

Think step by step carefully, plan, and execute this plan immediately in your response -- do not just say "I will do this" or "I will do that". Output to the REPL environment and especially the recursive LLM (`llm_query` in the REPL) as much as possible. Remember to explicitly answer the original query in your final answer."""

# %% ../nbs/rlm_lisette_v2.ipynb #b1e09038
from IPython.display import HTML

# Load Mermaid library once

def tool_mermaid(graph:str # string representing the chart to be displayed
    )->dict:
    '''Returns two blocks:
    - html_graph: this one need to be added where you want to dispaly the chart
    - html_run: this one need to be added at the end of the message and only "once" even if you generate multiple charts
    The result should be returned inline with the response without any markdown codeblock.
    ''' 
    return dict(html_graph=f'<div class="mermaid">{graph}</div>',
                html_run='<script>if (window.mermaid) mermaid.run();</script>') # fix thnx to @dgwyer

# %% ../nbs/rlm_lisette_v2.ipynb #17832b67
def mm(graph): return HTML('\n'.join(tool_mermaid(graph).values()))

# %% ../nbs/rlm_lisette_v2.ipynb #a38e15f0
def print_history(rlm):
    return Markdown("\n".join(map(_md, rlm.chat.hist)))

# %% ../nbs/rlm_lisette_v2.ipynb #b5c935df
from IPython.display import Markdown

# %% ../nbs/rlm_lisette_v2.ipynb #2769adae
def _md(x):
    if isinstance(x, litellm.types.utils.Message): x = x.__dict__

    role = x["role"]

    symbols = {"user": "😀", "assistant": "🤖", "tool": "🧰"}

    md = ""

    md += f"### {symbols[role]} {role}\n\n"
    if x["content"]:
        if role == "tool":
            md += ("```\n" + x["content"] + "\n```\n\n")
        else:
            md += (x["content"] + "\n\n")

    if "tool_calls" in x and x["tool_calls"]:
        c = json.loads(x["tool_calls"][0]["function"]["arguments"])["python_code"]
        md += f"```\n{c}\n```\n\n"

    md+= "---"

    return md

# %% ../nbs/rlm_lisette_v2.ipynb #954c4ac4
def generate_massive_context(num_lines: int = 1_000_000, answer: str = "1298418") -> str:
    print("Generating massive context with 1M lines...")
    
    # Set of random words to use
    random_words = ["blah", "random", "text", "data", "content", "information", "sample"]
    
    lines = []
    for _ in range(num_lines):
        num_words = random.randint(3, 8)
        line_words = [random.choice(random_words) for _ in range(num_words)]
        lines.append(" ".join(line_words))
    
    # Insert the magic number at a random position (somewhere in the middle)
    low = min(400000, max(0, num_lines - 1))
    high = min(600000, max(0, num_lines - 1))
    magic_position = random.randint(low, high)
    lines[magic_position] = f"The magic number is {answer}"
    
    print(f"Magic number inserted at position {magic_position}")
    
    return "\n".join(lines)

# %% ../nbs/rlm_lisette_v2.ipynb #1efb6c65
class RLM:
    def __init__(
        self,
        context: str,
        root_model="openai/gpt-oss-120b",
        recursive_model=None,
        temperature=0.0,
        base_url="https://openrouter.ai/api/v1",
        api_key=os.getenv("OPENROUTER_API_KEY"),
        extra_headers=None,
    ):
        self.context = context
        self.root_model = root_model
        self.recursive_model = recursive_model if recursive_model else root_model
        self.base_url = base_url
        self.api_key = api_key
        self.extra_headers = extra_headers
        self.shell = self._prep_shell()

        def run_repl(python_code: str) -> str:
            "Execute Python code in the REPL environment"
            result = self.shell.run_cell(python_code)
            if result.error_in_exec or result.error_before_exec:
                return f"Error: {result.error_in_exec or result.error_before_exec}"
            output = result.stdout or ""
            if result.result is not None:
                output += str(result.result)
            return output

        self.chat = Chat(
            model=self.root_model,
            tools=[run_repl],
            sp=REPL_SYSTEM_PROMPT,
            temp=temperature,
            api_key=self.api_key,
            #base_url=self.base_url,
            extra_headers=self.extra_headers,
        )

    def _prep_shell(self):
        def llm_query(query: str):
            msg = mk_msg(query)
            return litellm.completion(
                self.recursive_model,
                [msg],
                api_key=self.api_key,
                api_base=self.base_url,
                extra_headers=self.extra_headers,
            ).choices[0].message.content

        sh = get_shell()
        sh.user_ns["context"] = self.context
        sh.user_ns["llm_query"] = llm_query
        return sh

    def __call__(self, query: str, max_steps=2):
        return self.chat(query, max_steps=max_steps)
